summary: Simulating experiments by Iverson 2016 in the Material Point Method (MPM). A mass of dry sand is positioned atop a hill-slope and then suddenly released. The mass flows down the highly frictional slope and impacts a raised structural box at the bottom.
difficulty: 2
