summary: Simulating experiments by Lewis 2023 in the Material Point Method (MPM). A set of debris are placed into a steady-state flow in a flume. Impacts against a raised structural box are measured.
difficulty: 2
