summary: Forward sample a near-real time Celeris wave simulator. Replicates experiments on Seaside, Oregon, by Cox et al. 2008. Performed in Oregon State University's Directional Wave Basin.
difficulty: 1
